### PR TITLE
Reduce Docker image size by switching to miniconda base image

### LINKED ISSUE #29: Make image smaller
Currently our image is multi-GB in size. Waaay to much for this project.

### PR DESCRIPTION
**Pull request by adityasharad**
Closes #29.

Bring the image size down from ~3.12GB to ~1.83GB.
Explicitly install the `gcc` supplied by conda and ensure it is available to the shell when building Python package dependencies. (If this looks too messy, I'm happy to switch to the `python:3` image instead, which gives us a ~1.96GB image without the need to tweak the environment to get `gcc`.)

Based on #32 to avoid conflicts. Only the last two commits are new. This should be merged only after that PR.

### CODE REVIEW

**Comment by adityasharad** [comment]
> Can we just have a flat `/platform` instead of `.platform` and `.platform/docker`?

Good idea. I see #32 has implemented this suggestion, when that PR is merged I'll rebase this one.

**Comment by ckerr-IDM** [comment]
@adityasharad just merged, update away!

**Comment by adityasharad** [comment]
@cliffckerr done!
Re your comment about size, let's start with this change, and if we can identify other places to reduce the image size I'm happy to try those later.

**Comment by ckerr-IDM** [comment]
@adityasharad This looks great. Is it OK if I change my mind? :see_no_evil: I think `docker` would be useful for a decent fraction of users, but `platform` probably not. Could we move the `docker` folder to be top-level, instead of inside `.platform`?

**Comment by ckerr-IDM** [comment]
@adityasharad Also the commands listed don't seem to work, if I'm running them correctly
```
finzi:~/idm/covasim/.platform/docker> make pull-run
docker-compose pull covasim
Pulling covasim (covasim:latest)...
ERROR: pull access denied for covasim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:13: pull] Error 1
finzi:~/idm/covasim/.platform/docker> docker-compose pull covasim
Pulling covasim (covasim:latest)...
ERROR: pull access denied for covasim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ckerr-IDM** [comment]
So this sequence worked & has it up and running on Ubuntu:
```
docker-compose build
docker-compose up -d
```
Maybe we can just list that one way of doing things? cc @devclinton

**Comment by adityasharad** [comment]
> @adityasharad Also the commands listed don't seem to work, if I'm running them correctly
> 
> ```
> finzi:~/idm/covasim/.platform/docker> make pull-run
> docker-compose pull covasim
> Pulling covasim (covasim:latest)...
> ERROR: pull access denied for covasim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> make: *** [Makefile:13: pull] Error 1
> finzi:~/idm/covasim/.platform/docker> docker-compose pull covasim
> Pulling covasim (covasim:latest)...
> ERROR: pull access denied for covasim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```

I think I did the wrong thing in changing the image name - if you try to `pull` the image then it needs to get it from @jules2689's package registry.

**Comment by adityasharad** [comment]
- Reverted the change to the image name: this should fix `make pull`, `docker-compose pull covasim`, and `make pull-run`. Sorry about that.
- `make build` / `docker-compose build` and `make run` / `docker-compose up -d` should continue to work.

**Comment by cliffckerr** [comment]
Thanks @adityasharad , and last thing, can we have `docker` be a top-level folder instead of inside `platform`?

**Comment by adityasharad** [comment]
Moved `.platform/docker` to `docker` in [latest commit ](https://github.com/InstituteforDiseaseModeling/covasim/pull/34/commits/1e915edba521f84eacb2eaefd5e8cfe16517172e), also updated various readme links.

**Comment by ckerr-IDM** [comment]
Thanks @adityasharad !

**Pull request merged**
