### PR TITLE
Add NBeds to web app

### PR DESCRIPTION
**Pull request by gwincr11**
Motivation:
  - Added the ability to alter the n beds param from the web app.

To Do:
- [ ] Determine sane defaults
- [ ] Better tool tip?
- [ ] Where does this belong in the ui?

Related Issues:
  - https://github.com/InstituteforDiseaseModeling/covasim/issues/3

Changes:
  - Passed back a dict with some defaults from the default controller.

### CODE REVIEW

**Comment by gwincr11** [comment]
Screen Shot 2020-04-02 at 1 31 06 PM

**Comment by inc0** [comment]
Another thing would be to add intervention when we run out of beds. Intervention would increase mortality. We should be able to configure this mortality increase via web too

**Comment by gwincr11** [comment]
@inc0 Agreed, perhaps I can work on that in a separate pr. Keep pr's small and all.

**Comment by gwincr11** [comment]
If desired I can break it out into its own param section. I have that working locally as I thought it would be a good thing to do in order to better understand how data is flowing.
Screen Shot 2020-04-02 at 4 19 48 PM

**Comment by cliffckerr** [comment]
@gwincr11 @inc0 We're coordinating with a users group on what features they want to see in the app, stay tuned next week.

**Pull request closed without merging**
