### PR TITLE
Intervention test updates gh 204

### PR DESCRIPTION
**Pull request by CWiswell-IDM**
I'm not sure why this shows any conflicts with master, as I rebased off of IfDM master (the conflicting change had been the @unittest.skip() over two of the tests that are changed here).

I believe that I resolved these conflicts locally and force-pushed to my repository, which should have resolved this.

### CODE REVIEW

**Comment by CWiswell-IDM** [comment]
There we go.

**Comment by CWiswell-IDM** [comment]
Should resolve #204

**Comment by cliffckerr** [comment]
@CWiswell-IDM :facepalm: sorry, I see you did change that test. It looks like it's still being skipped though?

**Comment by CWiswell-IDM** [comment]
looking...

**Comment by cliffckerr** [comment]
Merged, thanks @CWiswell-IDM !

**Pull request merged**
