### PR TITLE
Add Data Scraper scripts

### PR DESCRIPTION
**Pull request by willf**
To quote the [Corona Data Scraper](https://coronadatascraper.com) web page,

> Corona Data Scraper pulls COVID-19 Coronavirus case data from verified sources, finds the corresponding GeoJSON features, and adds population data.

We transform this data for use in the Covasim parameter format. It is stored
in CSV-format. 

The following columns are present in the data:

- name: Apparently, a unique name for the data set
- level: level of the data (country, state, county, city)
- city: The city name
- county: The county or parish
- state: The state, province, or region
- country: [ ISO 3166-1 alpha-3 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
- population: The estimated population of the location
- lat: latitude
- long: longitude
- url: Data source
- aggregate
- tz: Time zone
- recovered: Cumulative number recovered (as of date)
- active: Cumulative number active (as of date)
- growthFactor:
- date: Date in yyyy-MM-dd text format
- day: Number of days since first reporting
- positives: Cumulative number of positive cases (as of date)
- death: Cumulative number of deaths (as of date)
- tests: Cumulative number of tests (as of date)
- new_positives: New positives on this date
- new_active: New active cases on this date
- new_death: Number of deaths on this date
- new_tests: New tests on this date

As of April 4, 2020, There are apparently 3280 data sets.

Data is placed in the `data` directory.
Loader is in the `data_loader` directory.

Partial completion of https://github.com/InstituteforDiseaseModeling/covasim/issues/43

### CODE REVIEW

**Comment by cliffckerr** [comment]
Haven't run it yet but beautifully clean implementation, thank you @willf !

**Comment by willf** [comment]
I added a European Centre for Disease Prevention and Control data loader.  

This adds data from 204 countries and territories, including Africa, Asia, the Americas, Europe, and Oceania. More details at: https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases

**Comment by willf** [comment]
Updated name of PR to be more accurate.

**Comment by cliffckerr** [comment]
@willf Thank you for this! Merged & looks great :)

**Pull request merged**
