### PR TITLE
Adds and fixes population tests

### PR DESCRIPTION
**Pull request by CWiswell-IDM**
Should be most of #133

### CODE REVIEW

**Comment by CWiswell-IDM** [comment]
@mfisher-idmod Take a look- this should get you off the hook for population testing
@Sv3tlana this should give you an idea what I'm doing with testing this stuff, but I can tell you more in 1:1 tomorrow.

**Comment by CWiswell-IDM** [comment]
The two tests that are failing are failing because synthpops is not available. I will disable them for now.

**Comment by mfisher-idmod** [comment]
> The two tests that are failing are failing because synthpops is not available. I will disable them for now.

If you have synthpops in your virtualenv, they do work. What are your thoughts on changing the GitHub Actions to set 'python setup.py develop full' to do the install with synthpops so we can run these types of synthpops integration tests?

**Comment by ckerr-IDM** [comment]
@mfisher-idmod @CWiswell-IDM my feeling is that this is probably too much effort until we can pip install synthpops

**Pull request merged**
