### PR TITLE
Adds tests for random and clustered population types using layers. 

### PR DESCRIPTION
**Pull request by CWiswell-IDM**
NOTE: the interesting test would be something with multiple layers, but not sure how to get that to work here.

You can see the place where I'd use synthpops, and add the layers ['h','s','w','c']

### CODE REVIEW

**Comment by cliffckerr** [comment]
@CWiswell-IDM only comment is to be sure to merge before you make a PR. in this case, master was updated with 30 new commits a full 18 minutes before you made this PR :laughing: 
```
finzi:~/idm/covasim/tests> gits
## CWiswell-IDM_unittest_intervention_change_beta_layers...CWiswell-IDM/unittest_intervention_change_beta_layers [ahead 30]
```

**Comment by CWiswell-IDM** [comment]
Arg! Always, always rebase first. :)

**Comment by CWiswell-IDM** [comment]
PS: The interesting test I hoped to do in here was to shut down layers one at a time (with some days in between) and see that when I'd gone through all of them, there was no more transmission, but I *think* the only poptype where that is interesting is synthpops?

**Comment by ckerr-IDM** [comment]
no that applies to `hybrid` too

**Pull request merged**
