### PR TITLE
add hyper parameter sweeps with Weights & Biases

### PR DESCRIPTION
**Pull request by hamelsmu**
Please review @cliffckerr @inc0 

related to: https://github.com/InstituteforDiseaseModeling/covasim/issues/49 

## Summary of changes

- Updated the README with Instructions
- Added Table of Contents to the README
- Added a directory `/sweep` which adds the code and configuration files for the example sweep.
- You can see example sweeps for this project at https://app.wandb.ai/github/covasim/sweeps

image

### Aside - Weights & Biases

- It is free for open source projects, so should be perfectly fine for other people who want to set this up. 
- These are the docs for sweeps: https://docs.wandb.com/sweeps
- This is pricing:  https://www.wandb.com/pricing

### CODE REVIEW

**Comment by hamelsmu** [comment]
We should also discuss [this question](https://github.slack.com/archives/C0110GFNJ6A/p1586477999191300)

>  has anyone given any thought about how they will ensure calibration or tuning is not overfitting the dataset?  For example the PR I have open with WandB overfits the parameters to the example data.  Perhaps subsetting the data by time or something like that with the last N days as a holdout set?

**Comment by Sv3tlana** [comment]
I'm looking at this right now, making sure a "me"-type person can follow instructions and run it.

**Comment by Sv3tlana** [comment]
@hamelsmu - I'm not seeing what you're seeing when I run sweep/sweep.py I just get one point in my resulting graphs? I also had to fix a data type mismatch in sim.py for this to work. Is there somehow we can talk directly?

**Comment by hamelsmu** [comment]
Are you available on slack? my handle is @hamelsmu

**Comment by Sv3tlana** [comment]
Update: I was able to run this with some fixes:                  
I had to update line 702 in sim.py
                    data_t = (np.array(self.data.index)-self['start_day'])/dt.timedelta(days=1)   
wrap self.data.index into an array and change which timedelta is being used to make the dates match

I also needed to run everything in administrator mode (inside Pycharm and my regular cmd prompt). 

It works! @hamelsmu is suggesting this package as something that can help us calibrate based on data. I'm not sure if there's something internal we want to use. He also raises a question of overfitting while using wamdb.

**Comment by cliffckerr** [comment]
@hamelsmu looks great, thanks! i removed wandb from requirements.txt since it's not a strict requirement and it has a _lot_ of dependencies to install...could've added it to `extras_require` but it already says in the readme to install it via pip so i figured the user could just do that :)

**Pull request merged**
