### PR TITLE
#192: fixed sidebar height not remaining fixed

### LINKED ISSUE #192: Sidebar height not maintained on scroll
See context here: 
https://github.com/InstituteforDiseaseModeling/covasim/pull/171#issuecomment-617372430

### PR DESCRIPTION
**Pull request by lgeorge-idm**
- On sidebar collapse and expand, graphs resize
- Scrolling with sidebar open does not resize the sidebar
- When sidebar grows vertically, scroll page and not sidebar
- Coverted toggle button to vertical bar on sidebar collapse 
- Fixed tooltip making sidebar footer overlap page footer

Fixes #192.

### CODE REVIEW

**Comment by lgeorge-idm** [comment]
### Landing


### Post-Execution



### Post Execution: Model/Advanced Params


### Sidebar Closed: Graphs

**Comment by lgeorge-idm** [comment]
@cliffckerr , I can fix the width. It's being responsive to the content, but I can see how that might be distracting.

On using black for the sidebar. I don't think there's enough contrast:
image

**Comment by cliffckerr** [comment]
@lgeorge-idm yeah, seeing it I agree about black -- let's leave gray for now

**Comment by lgeorge-idm** [comment]
Made all requested changes except for changing expand button black.

**Comment by cliffckerr** [comment]
@lgeorge-idm looking great, chevrons are :100:

**Pull request merged**
