### PR TITLE
Integrate docs changes to enable advanced search with autocomplete

### PR DESCRIPTION
**Pull request by bryanressler-idmod**

### CODE REVIEW

**Review by cliffckerr — CHANGES_REQUESTED** [review]
Thanks @bryanressler-idmod , looks good! 

Would it be possible to unpin the `readthedocs-sphinx-search` version?

This does seem to break my ability to build the docs locally, unfortunately:
```
Warning, treated as error:
the sphinx_search.extension extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
make: *** [Makefile:64: html] Error 2
```
This error is with `export NBSPHINX_EXECUTE=auto` and then `make html`

Might need to put the changes in an `if on_rtd:' block in conf.py unless this can be fixed

**Comment by bryanressler-idmod** [comment]
Thanks Cliff! I've unpinned the version.

**Comment by cliffckerr** [comment]
Thanks @bryanressler-idmod ! Re: the issue of the parallel build failing locally -- are you able to reproduce that?

**Comment by JSchripsema-IDM** [comment]
@bryanressler-idmod I looked at the doc build from your branch and it doesn't seem to be searching across other docsets or displaying the text under the search box. Does this require additional changes to be made to the parent docset?

**Review by JSchripsema-IDM — COMMENTED** [review]
The RTD search extension has been modified since this PR and now works as expected. Configuration syntax has changed so I think we should just close this out. @bryanressler-idmod

**Pull request closed without merging**
