### PR TITLE
Add docs gitignores

### PR DESCRIPTION
**Pull request by bryanressler-idmod**
Add a docs/.gitignores to allow docs to ignore some docs build projects without changing the base project .gitignores.

### CODE REVIEW

**Review by JSchripsema-IDM — APPROVED** [review]

**Comment by cliffckerr** [comment]
Thanks @bryanressler-idmod ! Good idea to have a docs-specific `.gitignore`. I don't think we want to ignore `tutorials` though, do we? (I also need to fix the failing tests here, which needless to say are not the fault of this PR!)

**Comment by cliffckerr** [comment]
A few example files are generated when the tutorials are built, but otherwise none of it is autogenerated if I remember correctly!

**Comment by bryanressler-idmod** [comment]
My bad. I will revise the PR.

Thanks again,
Bryan
________________________________

**Comment by JSchripsema-IDM** [comment]
Sorry, I should have caught that!

**Pull request closed without merging**
