### PR TITLE
Sensitivity

### PR DESCRIPTION
**Pull request by Pie923**
try adding time-varying test sensitivity

### CODE REVIEW

**Comment by martyn1fyles** [comment]
Hi Li, I think you may have opened this pull request incorrectly - this pull request is trying to merge our changes back into the main branch of Covasim (i.e, not one of ours), which I don't think we are quite ready to do yet

**Comment by cliffckerr** [comment]
Hi @Pie923 @martyn1fyles, intentional or not, it's great to know Covasim is getting some use and please feel free to get in touch if you have any questions, we'd be happy to help!

**Comment by martyn1fyles** [comment]
Hi @cliffckerr , thank you - covasim is a great bit of software. We've been extending it in a few areas and hopefully we can share some code at some point

**Comment by Pie923** [comment]
thank you! this should be a pull to our cloned repo

**Pull request closed without merging**
